version: '3.8'
services:
  django:
    container_name: medical_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery-beat
      - celery_worker
      - rabbitmq
    env_file:
      - .env
    links:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      retries: 3


  celery_worker:
    container_name: celery_worker
    build:
      context: .
    command: celery -A project.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      redis:
        condition: service_started


  celery-beat:
    container_name: celery_beat
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    command: celery -A project.celery beat --loglevel=DEBUG
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy